  name : mergeable
  on:
  # pull_request:
    push:
    paths:
    .github/workflows/mergeable.yml
   release:
   typs:
   - published
   Jobs:
 #-when: pull_request.*, pull_request_review.*
    validate:
      - do: request_review.*, 
      # pull_request.*
        # Enforce semantic release convention.
        test_include:
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$
          message: Semantic release conventions must be followed.
        # All todo check boxes must be checked.
        []=feat
        []=docs
        []=chore
        []=fix
        []=refactor
        []=test
        []=style
        []=pref
      - do: description
        can_include:
          regex: ^\[ \]
          on fail do:
          message: There are incomplete TODO task(s) unchecked.
      - do: approvals
        min:
          count: 1
        or:
            reviewers: [@I-Cat] 
   #       - required:
              reviewers: [@jusx]
   #       - required:
              reviewers: [@shine2lay]
