name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push latest
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mergeable:latest

      - name: Set version variable
        id: version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build and push tag
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mergeable:${{ steps.version.outputs.TAG }}
