name: Release

on:
  push:
    branches:
      - master
      - fix-docker-workflows

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      do_docker: ${{ steps.vars.outputs.IS_DOCKERHUB_PUSH }}
    steps:
      - name: Initialize workflow variables
        shell: bash
        run: |
          # work-around for inaccessible 'secrets' object for 'if'; see <https://github.community/t5/GitHub-Actions/jobs-lt-job-id-gt-if-does-not-work-with-env-secrets/m-p/38549>)
          unset IS_DOCKERHUB_PUSH
          if [ -z "$DOCKERHUB_PUSH" ]; then IS_DOCKERHUB_PUSH='false'; else IS_DOCKERHUB_PUSH='true' ; fi
          echo set-output name=IS_DOCKERHUB_PUSH::${IS_DOCKERHUB_PUSH}
          echo ::set-output name=IS_DOCKERHUB_PUSH::${IS_DOCKERHUB_PUSH}
        env:
          DOCKERHUB_PUSH: ${{ secrets.DOCKERHUB_PUSH }}
  docker:
    runs-on: ubuntu-latest
    needs: [init]
    if: ${{ needs.init.outputs.do_docker == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
